name: Mirror

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository from Codeberg
        run: |
          git clone --mirror https://codeberg.org/tomteb/CrissCross crisscross_mirror.git
          cd crisscross_mirror.git
          git push --mirror https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tomtebender/CrissCross.git
